# Generated by Django 5.0.6 on 2024-06-28 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_month', models.DateField()),
                ('sales_amount', models.FloatField()),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesperson')),
            ],
        ),
    ]
